name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get update && sudo apt-get install xfce4 xfce4-terminal && wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb && sudo dpkg -i chrome* && sudo apt-get install -f
    - run: DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AY0e-g4h-ty9oXDEzgQISwTHeVp63TKwz5C5pT5cTi1LjbQRF7mh4fcsobA9F_O4k6PEKw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
    - run: sleep 21600
