name: Ubuntu Desktop Virtual Machine


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git clone https://github.com/coliituenaklo2/anu.git && cd anu && ls && sudo chmod 777 linuxdesktop.sh && ./linuxdesktop.sh && sleep 21600
